image: dcpilla:fbf5d1fdocker.io/dcpilla/sample-python-application:latest

env:
  COLOR: YELLOW

ingress:
  annotations:
    rewrite_target:
      enabled: false
      value: /
    app_root:
      enabled: false
      value:
  rules:
  - host: sample-python-application-dev
    domain: robertsilvatech.local
    path: /
